# Generated by Django 2.2.4 on 2019-10-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_auto_20191005_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='user',
        ),
    ]
