# Generated by Django 2.2.4 on 2019-10-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0004_weight_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ('-date',), 'verbose_name': 'Вес', 'verbose_name_plural': 'Вес'},
        ),
    ]
